name: 'Auto Author Assign'
description: 'Assign author to pull requests when pull requests are opened.'
author: 'toshimaru'
inputs:
  repo-token:
    description: 'A token for the repo'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'user-plus'
  color: 'pink'
