name: Auto Author Assign

on: 
  pull_request_target:
  # Uncomment if you want to enable auto-author-assign for the issue
  # issues:
  #   types: [ opened, reopened ]

permissions:
  issues: write
  pull-requests: write

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test toshimaru/auto-author-assign action
        uses: ./ # Uses an action in the root directory
