on: [pull_request]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Assign author
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test toshimaru/auto-author-assign action
        uses: ./ # Uses an action in the root directory
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
