name: 'Auto Author Assign'
on: [pull_request_target]
permissions:
  contents: read
  pull-requests: write
jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test toshimaru/auto-author-assign action
        uses: ./ # Uses an action in the root directory
